info/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^entrar/', 'apps.usuarios.views.entrar', name='entrar'),
	url(r'^sair/$', 'apps.usuarios.views.sair'),
    
	url(r'^$', 'apps.website.views.home_page', name='home'),
	url(r'^busca/$', 'apps.website.views.busca', name='busca'),
	url(r'^oferta_gratis/$', 'apps.website.views.oferta_gratis', name='oferta_gratis'),

	url(r'^cadastre_se/$', 'apps.usuarios.views.cadastre_se', name='cadastre_se'),
	url(r'^painel/$', 'apps.usuarios.views.painel', name='painel'),
	url(r'^estado/(?P<cidade>.*)-(?P<estado>\w+)/$', 'apps.website.views.estado', name='estado'),
	# anuncio
	url(r'^criar_anuncio_gratis/$', 'apps.anuncio.views.criar_anuncio_gratis', name='criar_anuncio_gratis'),
	url(r'^anuncio_gratis/(?P<id>\d+)/$', 'apps.anuncio.views.anuncio_gratis', name='anuncio_gratis'),
	url(r'^planos/$', 'apps.anuncio.views.planos', name='planos'),

	# habilitando a visualização dentro dos arquivos em MEDIA - não usar em produção
	url(r'^media/(.*)/$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/anuncio/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.forms import ModelForm
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django import forms

class AnuncioGratis(models.Model):
	# ForeignKey
	usuario = models.ForeignKey(User, blank=True, null=True)
	
	# endereço
	estado = models.CharField(u'estado', max_length=2)
	cidade = models.CharField(u'cidade', max_length=100)
	endereco = models.CharField(u'endereço(logradouro)', max_length=255, help_text='Para uma melhor localização no mapa, preencha com nome da rua ou logradouro. Ex: Rua Martinho Estrela')
	numero = models.IntegerField(u'numero', help_text='numero do endereço do estabelecimento')
	bairro = models.CharField(u'bairro', max_length=50)
	cep = models.CharField(u'CEP', max_length=50)
	
	# dados do estabelecimento
	nome_empresa = models.CharField(u'nome da empresa', max_length=50)
	categoria = models.CharField(u'categoria', max_length=50, choices=(
		(u'Academias', u'Academias'), (u'Animais', u'Animais'),
		(u'assistencia Téc.', u'assistencia Téc.'), (u'Beleza/Estética', u'Beleza/Estética'),
		(u'Bares e Botecos', u'Bares e Botecos'), (u'Bebês e Crianças', u'Bebês e Crianças'),
		(u'Comunicação', u'Comunicação'), (u'Consultorias', u'Consultorias'), (u'Educação', u'Educação'),
		(u'Escritórios', u'Escritórios'), (u'Esportes', u'Esportes'), (u'Festas e Eventos', u'Festas e Eventos'),
		(u'Gráficas', u'Gráficas'), (u'Hotéis/Moteis', u'Hotéis/Moteis'), (u'Hobbies', u'Hobbies'),
		(u'Informática', u'Informática'), (u'Lazer', u'Lazer'), (u'Lanchonetes', u'Lanchonetes'),
		(u'Lojas e Varejo', u'Lojas e Varejo'), (u'Oficinas', u'Oficinas'), (u'Pizzarias', u'Pizzarias'),
		(u'Restaurantes', u'Restaurantes'), (u'Serviços', u'Serviços'), (u'Saúde/Bem Estar', u'Saúde/Bem Estar'),
		(u'Serv. Automotivos', u'Serv. Automotivos'), (u'Transportes', u'Transportes'), (u'Turismo', u'Turismo'),
		(u'Outros', u'Outros') ) )
	descricao_empresa= models.CharField(u'Breve descrição do negócio', max_length=200)
	email = models.EmailField(u'email', help_text='sera utilizado para recebimento de mensagens de usuários')
	telefone1 = models.CharField(u'telefone', max_length=50)
	telefone2 = models.CharField(u'telefone', max_length=50, blank=True, null=True)
	
	# dados do anuncio
	titulo = models.CharField(u'título do Anuncio', max_length=50)
	descricao = models.TextField(u'Descrição do Anúncio', max_length=1024)
	imagem = models.FileField(u'Imagem (150x50 pixels)', upload_to=settings.MEDIA_ROOT)
	
	# horarios
	dom = models.BooleanField(u'domingo')
	seg = models.BooleanField(u'segunda')
	ter = models.BooleanField(u'terça')
	qua = models.BooleanField(u'quarta')
	qui = models.BooleanField(u'quinta')
	sex = models.BooleanField(u'sexta')
	sab = models.BooleanField(u'sábado')
	abre = models.TimeField(u'abre às')
	fecha = models.TimeField(u'fecha às')

	# Pagamentos
	menor_preco = models.CharField(u'Menor Preço R$', max_length=6, default='1.00', help_text='Use "."(ponto) para separar as casas decimais.')
	maior_preco = models.CharField(u'Maior Preço R$', max_length=6, default='100.00', help_text='Use "."(ponto) para separar as casas decimais.')

	# redes sociais
	facebook = models.URLField(u'facebook', blank=True, null=True, default='')
	twitter = models.URLField(u'twitter', blank=True, null=True, default='')
	plus = models.URLField(u'Google+', blank=True, null=True, default='')
	insta = models.URLField(u'instagram', blank=True, null=True, default='')
	like = models.IntegerField(u'like', blank=True, null=True, default=0)
	unlike = models.IntegerField(u'unlike', blank=True, null=True, default=0)

	# Fields de auditoria
	status = models.BooleanField(u'Ativo?', default=True)
	created_on = models.DateTimeField(auto_now_add=True)
	updated_on = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.titulo

	def telefones(self):
		return "%s / %s" %(self.telefone1, self.telefone2)

	def endereco_completo(self):
		return "%s, %s - %s, %s - %s, %s" %(self.endereco, self.numero, self.bairro, self.cidade, self.estado, self.cep)

class Capa(models.Model):
    anuncio = models.OneToOneField(AnuncioGratis)
    imagem = models.FileField('imagem')

class CapaForm(ModelForm):
	class Meta:
		model = Capa
		exclude = ['anuncio']
		widgets = {'imagem' : forms.FileInput(attrs={'class':'form-control'}),}
		
class AnuncioGratisForm(ModelForm):
	class Meta:
		model = AnuncioGratis
		exclude = ['usuario', 'like', 'unlike', 'status', 'created_on', 'updated_on']
		widgets = {
			'estado' : forms.Select(attrs = {'class': 'form-control'}),
			'cidade' : forms.Select(attrs = {'class': 'form-control'}),
            'endereco' : forms.TextInput(attrs = {'class': 'form-control'}),
            'numero' : forms.NumberInput(attrs={'class':'input-group'}),
            'bairro' : forms.TextInput(attrs={'class':'form-control', 'placeholder': 'bairro'}),
            'cep' : forms.TextInput(attrs={'class':'input-group'}),
            'nome_empresa' : forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'nome da empresa/negócio'}),
            'descricao_empresa' : forms.TextInput(attrs = {'class': 'form-control'}),
            'descricao_empresa' : forms.TextInput(attrs = {'class': 'form-control'}),
            'email' : forms.TextInput(attrs = {'class': 'form-control'}),
            'telefone1' : forms.TextInput(attrs = {'class': 'input-group'}),
            'telefone2' : forms.TextInput(attrs = {'class': 'input-group'}),
            'titulo' : forms.TextInput(attrs = {'class': 'form-control'}),
            'descricao' : forms.Textarea(attrs = {'class': 'form-control'}),
            'imagem' : forms.FileInput(attrs={'class':'form-control'}),
            'dom' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'seg' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'ter' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'qua' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'qui' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'sex' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'sab' : forms.CheckboxInput(attrs={'class':'input-group'}),
            'menor_preco' : forms.NumberInput(attrs={'class':'input-group'}),
            'maior_preco' : forms.NumberInput(attrs={'class':'input-group'}),
            'abre' : forms.TextInput(attrs={'class':'input-group'}),
            'fecha' : forms.TextInput(attrs={'class':'input-group'}),
            'facebook' : forms.TextInput(attrs = {'class': 'form-control'}),
            'twitter' : forms.TextInput(attrs = {'class': 'form-control'}),
            'plus' : forms.TextInput(attrs = {'class': 'form-control'}),
            'insta' : forms.TextInput(attrs = {'class': 'form-control'}),
            'categoria' : forms.Select(attrs = {'class': 'input-group'}),
        }
# área para as signals
# ajustando o campo imagem no model Trabalhos para que este não capture todo o endereço da imagem
def nome_imagem(sender, instance, signal, *args, **kwargs):
	# checando se a instância possui os atributos image e id
	if instance.id and hasattr(instance, 'imagem') and not hasattr(instance, '_already_save'):
		meu_local = str(instance.imagem).split('/').pop()
		instance.imagem = meu_local
		instance._already_save = True
		instance.save()

# chamada ao signal post_save
post_save.connect(nome_imagem, sender=AnuncioGratis)
post_save.connect(nome_imagem, sender=Capa)

apps/anuncio/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

@login_required(login_url='/entrar/')
def criar_anuncio_gratis(request):
	if AnuncioGratis.objects.filter(status=True).filter(usuario_id=request.user).count() > 0:
		return HttpResponseRedirect(reverse('painel'))

	form = AnuncioGratisForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('painel'))

	return render(request, 'criar_anuncio_gratis.html', {'form': form, 'request': request})

def planos(request):
	return render(request, 'planos.html')

def anuncio_gratis(request, id):
	anuncio = AnuncioGratis.objects.get(pk=id)
	return render(request, 'anuncio_gratis.html', {'anuncio': anuncio})

apps/anuncio/templates/ad_sense_anuncio.html
	<!-- ADSENSE --> 
	<div class="adsprm"> 
		<div class="adsprmcd"> 
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- plansinfo -->
				<ins class="adsbygoogle"
				style="display:inline-block;width:728px;height:90px"
				data-ad-client="ca-pub-4072787528957271"
				data-ad-slot="7919976462">
				</ins>
			<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
		</div>
	</div><!-- FIM ADSENSE -->

apps/anuncio/templates/criar_anuncio_gratis.html
{% extends "base_interno.html" %}
{% load staticfiles %}
{% block conteudo %}
{% include "painel_usuario.html" %}

{% block css_extra %}
		<!-- Bootstrap 3.3.5 -->
	<link rel="stylesheet" href={% static "css/botstraps/bootstrap/css/bootstrap.min.css" %}>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<!-- daterange picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/daterangepicker/daterangepicker-bs3.css" %}>
	<!-- iCheck for checkboxes and radio inputs -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/iCheck/all.css" %}>
	<!-- Bootstrap Color Picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/colorpicker/bootstrap-colorpicker.min.css" %}>
	<!-- Bootstrap time Picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/timepicker/bootstrap-timepicker.min.css" %}>
	<!-- Select2 -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/select2/select2.min.css" %}>
	<!-- Theme style -->
	<link rel="stylesheet" href={% static "css/botstraps/dist/css/AdminLTE.min.css" %}>
	<!-- AdminLTE Skins. Choose a skin from the css/skins
		 folder instead of downloading all of them to reduce the load. -->
	<link rel="stylesheet" href={% static "css/botstraps/dist/css/skins/_all-skins.min.css" %}>

	<!-- label do formulário -->
	<link rel="stylesheet" href={% static "css/formulario_anuncio.css" %}>

{% endblock css_extra %}

{% block extra_js %}
	
	<script type="text/javascript" src={% static "js/masked_input.js" %}></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_telefone1').mask('(99) 9999-9999');
			$('#id_telefone2').mask('(99) 9999-9999');
			$('#id_cep').mask('99999-999');
			$('#id_abre').mask('99:99');
			$('#id_fecha').mask('99:99');
		});
	</script>

{% endblock extra_js %}

 <!-- DIV QUE CENTRALIZA --> 
<div class="sitctro"> 
{% include "ad_sense_anuncio.html" %}

	<div style="margin-top:15px;" class="ttlepq2">
		<div style="margin-left:20px; background-image:url(/static/img/smtv2msg.png);"  class="icttlq"> </div>
		<p style="color:#666; font-size:18pt; font-family: 'Open Sans', sans-serif; margin-left:10px; float:left;">Formulário de Anuncio InfoNegócio </p>
	</div>
	<!-- CAIXA DE MENSAGENS -->  
	<div class="cxmsg">
	 
		<div class="btcxmsg"> </div>
	 	<!-- BASE FORM RESPONS -->
		<div class="bngform">	
			<!-- form -->
			<div class="bngformlaesq"> 

				<!-- line para criação -->
				<div class="row bs-wizard" style="border-bottom:0; margin-left:70px;">
					<div class="col-xs-3 bs-wizard-step complete">
						<div style="color:#06C;" class="text-center bs-wizard-stepnum">
							Informar Dados
						</div>
						<div class="progress">
							<div class="progress-bar"></div>
						</div>
						<a href="#" class="bs-wizard-dot"></a>
					</div>

					<div  class="col-xs-3 bs-wizard-step disabled"><!-- active -->
						<div class="text-center bs-wizard-stepnum">Envio e Avaliação</div>
						<div style="background-color:#D8D8D8;" class="progress">
							<div class="progress-bar"></div>
						</div>
						<a href="#" style="background-color:#D8D8D8;" class="bs-wizard-dot"></a>
					</div>

					<div  class="col-xs-3 bs-wizard-step disabled"><!-- active -->
						<div class="text-center bs-wizard-stepnum">
							Publicação do Anúncio
						</div>
						<div style="background-color:#D8D8D8;" class="progress">
							<div class="progress-bar"></div>
						</div>
						<a href="#" style="background-color:#D8D8D8;" class="bs-wizard-dot"></a>
					</div>
				</div>
				<!-- fim line criacao -->  
				<form role="form" action='.' method='POST' enctype='multipart/form-data'> 
					<div class="box-body">
						<div>
							<br>
							{% csrf_token %}
							{{form.as_p}}
						</div>
						<hr class="colorgraph">
						<div class="row">
							<div class="col-xs-12 col-md-6"><input type="submit" value="Salvar" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
							<div class="col-xs-12 col-md-6"><a href="/painel" class="btn btn-success btn-block btn-lg">Cancelar</a></div>
						</div>
					</div>
				</form>
			</div>
	<Div class="sprbton"> </Div>
	</div>
</div> <!-- FIM DIV QUE CENTRALIZA --> 
  <Div class="separcont"> </Div>
</div>
		
{% endblock conteudo %}

apps/anuncio/templates/diferenciais.html
			<!-- BOX DIFERENCIAIS, OPICIONAL  -->    
			<div class="dif"> 
				<div class="difd">
					<div class="ribss"> 
						<div class="ribnme">
							<p style="color:#FFF; font-size:15pt; font-family: 'Ubuntu', sans-serif; margin-left:20px; margin-top:5px; text-shadow: 0 0 1px rgba(0,0,0,.35);">
								Diferenciais
							</p>
						</div>
					</div>
					<div class="contudtext"> 
						<p style="color:#838383; font-size:13px; margin:20px; text-align:justify; margin-top:5px; float:left;">
							Estacionamento Grátis, Ar condicionado, Atendimento para Deficiente Físico, Sala de fumantes, entre outros. Delivery
						</p>
					</div>
				</div>
			</div>
			<div class="shaap"> </div>
 			<!-- FIM BOX DIFERENCIAIS, OPICIONAL  --> 

apps/anuncio/templates/galeria_fotos.html
					<!-- GALERIA DE FOTOS DO ANUNCIO-->
					<div   class="albfoto"> 
						<div  class="amarra-ftss">
							<div id="amazingcarousel-5" style=" display:none;position:relative;width:100%;max-width:415px;margin:0px auto 0px;">
								<div class="amazingcarousel-list-container">
									<ul class="amazingcarousel-list">
										
										<div class="lightboxxx">
										<!--FOTO 1-->
											<li class="amazingcarousel-item">
												<div class="amazingcarousel-item-container">
													<div class="amazingcarousel-image">
														<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
														<a href="/static/img/foto-anuncio/1-lightbox.jpg" class="html5lightbox" data-group="amazingcarousel-5">
														<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
														<!-- IMAGEM EM MINIATURA-->
														<img style="width:67px; height:63px;" src="/static/img/foto-anuncio/1-lightbox.jpg"; /> </a></div>
														<!-- IMAGEM EM MINIATURA-->
														<div class="amazingcarousel-title">
														</div>
													<div class="amazingcarousel-description"></div>         
												</div>
											</li>
										</div>
										<!-- FIM FOTO 1-->
										<!--FOTO 1-->
										<li class="amazingcarousel-item">
											<div class="amazingcarousel-item-container">
												<div class="amazingcarousel-image">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<a href="/static/img/foto-anuncio/1-lightbox.jpg" class="html5lightbox" data-group="amazingcarousel-5">
														<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
														<!-- IMAGEM EM MINIATURA-->
														<img style="width:67px; height:63px;" src="/static/img/foto-anuncio/1-lightbox.jpg"; />
													</a>
												</div>
													<!-- IMAGEM EM MINIATURA-->
												<div class="amazingcarousel-title"></div>
												<div class="amazingcarousel-description"></div>                   
 											</div>
										</li>
										<!-- FIM FOTO 1-->
										<!--FOTO 2-->
										<li class="amazingcarousel-item">
											<div class="amazingcarousel-item-container">
												<div class="amazingcarousel-image">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<a href="/static/img/foto-anuncio/1-lightbox.jpg" class="html5lightbox" data-group="amazingcarousel-5">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<!-- IMAGEM EM MINIATURA-->
														<img style="width:67px; height:63px;" src="/static/img/foto-anuncio/1-lightbox.jpg"; />
													</a>
												</div>
												<!-- IMAGEM EM MINIATURA-->
												<div class="amazingcarousel-title"></div>
												<div class="amazingcarousel-description"></div>
											</div>
										</li>
										<!-- FIM FOTO 2-->
										<!--FOTO 2-->
										<li class="amazingcarousel-item">
											<div class="amazingcarousel-item-container">
												<div class="amazingcarousel-image">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<a href="/static/img/foto-anuncio/1-lightbox.jpg" class="html5lightbox" data-group="amazingcarousel-5">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<!-- IMAGEM EM MINIATURA-->
														<img style="width:67px; height:63px;" src="/static/img/foto-anuncio/1-lightbox.jpg"; />
													</a>
												</div>
												<!-- IMAGEM EM MINIATURA-->
												<div class="amazingcarousel-title"></div>
												<div class="amazingcarousel-description"></div>
											</div>
										</li>
										<!-- FIM FOTO 2-->
										<!--FOTO 2-->
										<li class="amazingcarousel-item">
											<div class="amazingcarousel-item-container">
												<div class="amazingcarousel-image">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<a href="/static/img/foto-anuncio/1-lightbox.jpg" class="html5lightbox" data-group="amazingcarousel-5">
													<!-- IMAGEM LIGHT BOX ATIVA GRANDE-->
													<!-- IMAGEM EM MINIATURA-->
														<img style="width:67px; height:63px;" src="/static/img/foto-anuncio/1-lightbox.jpg"; />
													</a>
												</div>
												<!-- IMAGEM EM MINIATURA-->
												<div class="amazingcarousel-title"></div>
												<div class="amazingcarousel-description"></div>
											</div>
										</li>
										<!-- FIM FOTO 2-->
									</ul>
									<div class="amazingcarousel-prev"></div>
									<div class="amazingcarousel-next"></div>
								</div>
								<div class="amazingcarousel-nav"></div>

							</div>
						</div>
					</div>
					<!-- FIM GALERIA DE FOTOS DO ANUNCIO-->

apps/anuncio/templates/patrocinados.html
	<div class="nmptroc"> <span style="color:#09C; margin-left:17px; font-size:9px; "> Anúncios Patrocinados </span> </div>
	
	<div style="height:110px;" class="promm">  <!-- PATROCINADOS ALEATORIOS -->
		
		<a target="_blank" href="#">
			<div style="margin-left:5px;" class="bxpromo">   <!-- PATROCINADO 1 --> 
				<div class="patrocfto">
					<img style="width:90px; height:85px; border: thin solid; padding: 5px; border-color:#CCC;" src="/static/img/ofertas/01.jpg">
				</div> <!-- FOTO DO PATROCINADO --> 
   
				<div class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:13px; color:#C30; margin-top:1px;">
						REI DO MOCOTÓ E DOBRADINHA
					</p>
				</div> <!-- TITULO PATROCINADO --> 
   
				<div class="desccr-patr"> <!-- BREVE DESCRICAO DO PATROCINADO --> 
					<p style="font-size:11px; color:#666; " >
						Casa do norte e restaurante nordestino com 39 anos detradição em São Paulo. Somos esp... 
					</p>
				</div>   
				<div style="margin-top:-1px;" class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:11px; color:#39C;">
						São Paulo - SP
					</p>
				</div> <!-- LOCAL PATROCINADO --> 
			</div> 
			<div class="seppro"></div> 
		</a> <!-- FIM PATROCINADO 1 -->

		<a target="_blank" href="#"> 
			<div style="margin-left:5px;" class="bxpromo">   <!-- PATROCINADO 1 --> 
				<div class="patrocfto">
					<img style="width:90px; height:85px; border: thin solid; padding: 5px; border-color:#CCC;" src="/static/img/ofertas/01.jpg">
				</div> <!-- FOTO DO PATROCINADO --> 
   
				<div class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:13px; color:#C30; margin-top:1px;">
						REI DO MOCOTÓ E DOBRADINHA
					</p>
				</div> <!-- TITULO PATROCINADO --> 
   
				<div class="desccr-patr"> <!-- BREVE DESCRICAO DO PATROCINADO --> 
					<p style="font-size:11px; color:#666; " >
						Casa do norte e restaurante nordestino com 39 anos detradição em São Paulo. Somos esp... 
					</p>
				</div>
   
				<div style="margin-top:-1px;" class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:11px; color:#39C;">
						São Paulo - SP
					</p>
				</div> <!-- LOCAL PATROCINADO --> 
			</div> 
			<div class="seppro"></div> 
		</a> <!-- FIM PATROCINADO 1 -->

		<a target="_blank" href="#"> 
			<div style="margin-left:5px;" class="bxpromo">   <!-- PATROCINADO 1 --> 
				<div class="patrocfto">
					<img style="width:90px; height:85px; border: thin solid; padding: 5px; border-color:#CCC;" src="/static/img/ofertas/01.jpg">
				</div> <!-- FOTO DO PATROCINADO --> 

				<div class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:13px; color:#C30; margin-top:1px;">
						REI DO MOCOTÓ E DOBRADINHA
					</p>
				</div> <!-- TITULO PATROCINADO --> 

				<div class="desccr-patr"> <!-- BREVE DESCRICAO DO PATROCINADO --> 
					<p style="font-size:11px; color:#666; " >
						Casa do norte e restaurante nordestino com 39 anos detradição em São Paulo. Somos esp... 
					</p>
				</div>

				<div style="margin-top:-1px;" class="titulo-patr">
					<p style="font-family: 'Ubuntu', sans-serif; font-size:11px; color:#39C;">
						São Paulo - SP
					</p>
				</div> <!-- LOCAL PATROCINADO --> 
			</div> 
			<div class="seppro"></div> 
		</a> <!-- FIM PATROCINADO 1 -->
	</div> <!-- FIM DO PATROCINADOS ALEATORIOS -->