info/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^entrar/', 'apps.usuarios.views.entrar', name='entrar'),
	url(r'^sair/$', 'apps.usuarios.views.sair'),
    
	url(r'^$', 'apps.website.views.home_page', name='home'),
	url(r'^busca/$', 'apps.website.views.busca', name='busca'),
	url(r'^oferta_gratis/$', 'apps.website.views.oferta_gratis', name='oferta_gratis'),

	url(r'^cadastre_se/$', 'apps.usuarios.views.cadastre_se', name='cadastre_se'),
	url(r'^painel/$', 'apps.usuarios.views.painel', name='painel'),
	url(r'^estado/(?P<cidade>.*)-(?P<estado>\w+)/$', 'apps.website.views.estado', name='estado'),
	# anuncio
	url(r'^criar_anuncio_gratis/$', 'apps.anuncio.views.criar_anuncio_gratis', name='criar_anuncio_gratis'),
	url(r'^anuncio_gratis/(?P<id>\d+)/$', 'apps.anuncio.views.anuncio_gratis', name='anuncio_gratis'),
	url(r'^planos/$', 'apps.anuncio.views.planos', name='planos'),

	# habilitando a visualização dentro dos arquivos em MEDIA - não usar em produção
	url(r'^media/(.*)/$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/usuarios/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from localflavor.br.forms import STATE_CHOICES

class Usuario(User):
	nome = models.CharField(u'nome completo', max_length=120)
	telefone = models.CharField(u'contato', max_length=50, unique=True)
	tipo_conta = models.CharField(u'tipo de conta', max_length=50, 
		choices=(('free', 'free'), ('bronze', 'bronze'), ('prata', 'prata'), ('ouro', 'ouro')), default='free')
	# Fields de auditoria
	created_on = models.DateTimeField(auto_now_add=True)
	updated_on = models.DateTimeField(auto_now=True)

class CadastrarUsuarioForm(UserCreationForm):

	class Meta:
		model = Usuario
		fields = ('username', 'email','nome', 'telefone')
		widgets = {
			'username': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Username'}),
			'email': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'E-Mail'}),
			'nome': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Nome completo'}),
			'endereco': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'endereço completo'}),
			'cep': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'CEP'}),
			'bairro': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'bairro'}),
			'telefone': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'telefone'}),

		}
	def __init__(self, *args, **kwargs):
		super(CadastrarUsuarioForm, self).__init__(*args, **kwargs)
		self.fields['password1'].widget = forms.PasswordInput(attrs={
			'class': 'form-control',
			'placeholder': '****'})
		self.fields['password2'].widget = forms.PasswordInput(attrs={
			'class': 'form-control',
			'placeholder': '****'})

apps/usuarios/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import *
from apps.anuncio.models import AnuncioGratis
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

def cadastre_se(request):
	form = CadastrarUsuarioForm(request.POST or None)

	if form.is_valid() and (request.POST['estado'] != '' or request.POST['cidade'] != ''):
		form = form.save(commit=False)
		form.estado = request.POST['estado']
		form.cidade = request.POST['cidade']
		form.save()
		return HttpResponseRedirect(reverse('entrar'))
	
	return render(request, 'cadastre_se.html', {'form': form})

# login no sistema
def entrar(request):
	send_mail('Teste', 'Teste de envio de email com Django', 'atrito12@gmail.com', ['atrito12@gmail.com', 'atrito12@gmail.com'])
	# checando se o usuário já realizou o login e tomanda a decisão adequada
	if request.user.is_authenticated():
		if request.user.is_superuser:
			return HttpResponseRedirect(reverse('administracao'))
		else:
			return HttpResponseRedirect(reverse('painel'))


	form = AuthenticationForm(request.POST or None)
	erro = False

	if request.method == 'POST':
		usuario = authenticate(username=request.POST['username'], password=request.POST['password'])

		if usuario is not None and usuario.is_active:
			login(request, usuario)
			
			# redirecionar para local adequado
			if usuario.is_superuser:
				return HttpResponseRedirect('/administracao/')
			else:
				# redireciona para área do cliente
				return HttpResponseRedirect('/painel/')

		else: erro = True
	
	return render(request, 'entrar.html', {'form': form, 'erro': erro})

# logout no sistema
def sair(request):
	logout(request)
	return HttpResponseRedirect(reverse('home'))

@login_required(login_url='/entrar/')
def painel(request):
	anuncio_gratis = AnuncioGratis.objects.filter(status=True).filter(usuario_id=request.user)
	return render(request, 'painel.html', {'anuncio_gratis': anuncio_gratis})

apps/usuarios/templates/cadastre_se.html
{% extends "base_interno.html" %}
{% load staticfiles %}
{% block conteudo %}

{% block css_extra %}
		<!-- Bootstrap 3.3.5 -->
	<link rel="stylesheet" href={% static "css/botstraps/bootstrap/css/bootstrap.min.css" %}>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<!-- daterange picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/daterangepicker/daterangepicker-bs3.css" %}>
	<!-- iCheck for checkboxes and radio inputs -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/iCheck/all.css" %}>
	<!-- Bootstrap Color Picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/colorpicker/bootstrap-colorpicker.min.css" %}>
	<!-- Bootstrap time Picker -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/timepicker/bootstrap-timepicker.min.css" %}>
	<!-- Select2 -->
	<link rel="stylesheet" href={% static "css/botstraps/plugins/select2/select2.min.css" %}>
	<!-- Theme style -->
	<link rel="stylesheet" href={% static "css/botstraps/dist/css/AdminLTE.min.css" %}>
	<!-- AdminLTE Skins. Choose a skin from the css/skins
		 folder instead of downloading all of them to reduce the load. -->
	<link rel="stylesheet" href={% static "css/botstraps/dist/css/skins/_all-skins.min.css" %}>

	<!-- label do formulário -->
	<link rel="stylesheet" href={% static "css/formulario_anuncio.css" %}>

{% endblock css_extra %}

{% block extra_js %}
	
	<script type="text/javascript" src={% static "js/masked_input.js" %}></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_telefone').mask('(99) 9999-9999');
		});
	</script>

{% endblock extra_js %}

 <!-- DIV QUE CENTRALIZA --> 
<div class="sitctro"> 
{% include "ad_sense_anuncio.html" %}

	<div style="margin-top:15px;" class="ttlepq2">
		<div style="margin-left:20px; background-image:url(/static/img/smtv2msg.png);"  class="icttlq"> </div>
		<p style="color:#666; font-size:18pt; font-family: 'Open Sans', sans-serif; margin-left:10px; float:left;">Formulário de Cadastro </p>
	</div>
	<!-- CAIXA DE MENSAGENS -->  
	<div class="cxmsg">
	 
		<div class="btcxmsg"> </div>
	 	<!-- BASE FORM RESPONS -->
		<div class="bngform">	
			<!-- form -->
			<div class="bngformlaesq">  
				<form role="form" action='.' method='POST' enctype='multipart/form-data'> 
					<div class="box-body">
						<div>
							<br>
							{% csrf_token %}
							{{form.as_p}}
						</div>
						<hr class="colorgraph">
						<div class="row">
							<div class="col-xs-12 col-md-6"><input type="submit" value="Cadastre-se" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
							<div class="col-xs-12 col-md-6"><a href="/entrar" class="btn btn-success btn-block btn-lg">Entre</a></div>
						</div>
					</div>
				</form>
			</div>
	<Div class="sprbton"> </Div>
	</div>
</div> <!-- FIM DIV QUE CENTRALIZA --> 
  <Div class="separcont"> </Div>
</div>
		
{% endblock conteudo %}

apps/usuarios/templates/entrar.html
{% extends "base_interno.html" %}
{% load staticfiles %}
{% block conteudo %}
{% block cssextra %}
	<link rel="stylesheet" type="text/css" href={% static "css/master-interno.css" %}>
{% endblock cssextra %}

<!-- DIV SITE CONTEUDO -->
<div  class="separ-topo2"> </div>
	<div class="banner-cliente"> <!-- AQUI O CLIENTE MUDA O BANNER DO ANUNCIO DELE    --> 		
		<div class="bgform"> <!-- BG FORM    -->
			<div style="margin:auto;" class="container">
	{% include "ad_sense_anuncio.html" %}
				<div class="row">
					<div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
						<form action='.' method='POST'>
							<h2>Seja bem vindo <small>use seus dados para logar ou registrar para uma conta gratuita</small></h2>
							<hr class="colorgraph">
							{% csrf_token %}
							{{form.as_p}}
							<div class="row">
								<div class="col-xs-8 col-sm-9 col-md-9">Use seu <strong class="label label-primary">Nome de Usuario e senha</strong> para ter acesso a sua conta.<a href="#" data-toggle="modal" data-target="#t_and_c_m">Termos de Uso.</a> 
									{{request.POST.estado}}
								</div>
							</div>	
							<hr class="colorgraph">
								{% if erro %}
									<div class='alert alert-danger'>Login ou senha incorretos! Por favor tente novamente.</div>
								{% endif %}
							<div class="row">
								<div class="col-xs-12 col-md-6">
									<input type="submit" value="Entrar" class="btn btn-primary btn-block btn-lg" tabindex="7">
								</div>
								<div class="col-xs-12 col-md-6"><a href="/cadastre_se" class="btn btn-success btn-block btn-lg">Registrar</a></div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>    
	</div> <!-- FIM BANNER CLIENTE    -->
		
{% endblock conteudo %}

apps/usuarios/templates/painel.html
{% extends "base_interno.html" %}
{% load staticfiles %}
{% block conteudo %}
{% include "painel_usuario.html" %}
	<!-- DIV QUE CENTRALIZA --> 
	<div class="sitctro">
		{% if anuncio_gratis %}
			<div style="background-color:#096;" class="nav-aviso"> 
				<div style="background-color:#066;" class="navdesgstat"> </div>
				<!-- TXT STATUS PAINEL ZERO --> 	
				<p style="color:#FFF; margin:15px; font-size:9pt; font-family:arial; text-shadow: 0 0 1px rgba(0,0,0,.35);">
					<strong>Atenção:<br>
						Aqui você pode Editar, Criar ou Excluir o seu anúncio. Você pode tambem destacar e melhorar o seu anuncio escolhendo um de nossos planos de contas Premium <a title="Contrate um Plano Premium" style="color:#FC6;" href="/planos">Aqui!</a>
					</strong>
				</p>
				<!-- TXT STATUS PAINEL ZERO -->     
			</div>	
		{% else %}
		<div class="nav-aviso"> 
			<div class="navdesgstat"> </div>
		 <!-- TXT STATUS PAINEL ZERO --> 
			<p style="color:#FFF; margin:15px; font-size:9pt; font-family: 'Open Sans', sans-serif; text-shadow: 0 0 1px rgba(0,0,0,.35);">
				<strong>
					Atenção:<br>
					Você ainda não publicou anúncios nesta conta, por isso algumas funcionalidades não estarão ativas, Basta escolher um tipo de anúncio e publica-lo para que o painel fique ativo. Você pode escolher um dos planos de anúncios
					<a title="Planos de Anúncios" style="color:#FFF;" href="#">
						aqui!
					</a>
				</strong>
			</p>
		<!-- TXT STATUS PAINEL ZERO -->  
		</div>
		{% endif %}
		
		<div class="ttlepainel"> 
			<h2 style="text-align:center; margin-top:5px; color:#666; font-family: 'Open Sans', sans-serif;">
				Painel do Usuário
			</h2>
		</div>
		
		<div class="nvboxstat"> 	
			<!-- BOX STATS ANUNCIOS NUMEROS --> 
			<div style="background-image:url(/static/img/bx1.png);" class="bxst"> 
			<!-- QUANTOS ANUNCIOS --> 
				<div class="nmberancio"> 
					<p style="color:#FFF; margin-top:-15px; font-size:45pt; font-family: 'Ubuntu', sans-serif; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						00 
					</p> 
				</div>

				<div class="dvnme"> 
					<p style="color:#FFF; text-align:center; text-shadow: 0 0 1px rgba(0,0,0,.35); font-family: 'Ubuntu', sans-serif; margin-top:-1px;">
						Anúncios ativos
					</p>
				</div>
			</div>
			<!-- BOX STATS ANUNCIOS NUMEROS --> 

			<!-- BOX VISUALIZARAM ANUNCIO APENAS PARA PGO --> 
			<div style="background-image:url(/static/img/bx2.png);" class="bxst2"> 
				<!-- QUANTAS VISITAS --> 
				<div class="nmberancio2"> 
					<p style="color:#FFF; margin-top:-5px; font-size:24pt; font-family: 'Ubuntu', sans-serif; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						00
					</p> 
				</div>

				<div class="dvnme2"> 
					<p style="color:#FFF; margin-left:10px; font-size:13px; font-family: 'Ubuntu', sans-serif; margin-top:-8px; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						Pessoas visualizaram seu Anúncio
					</p>
				</div>
			</div>
	<!-- BOX VISUALIZARAM ANUNCIO APENAS PARA PGO --> 

			<!-- BOX VISUALIZARAM ANUNCIO APENAS PARA PGO --> 
			<div style="background-image:url(/static/img/bx3.png);" class="bxst2"> 
				<!-- QUANTAS VISITAS --> 
				<div class="nmberancio2"> 
					<p style="color:#FFF; margin-top:-5px; font-size:24pt; font-family: 'Ubuntu', sans-serif; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						00
					</p> 
				</div>

				<div class="dvnme2"> 
					<p style="color:#FFF; margin-left:10px; font-size:13px; font-family: 'Ubuntu', sans-serif; margin-top:-8px; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						Ofertas Publicadas
					</p>
				</div>

				<!-- DESATIVADO POR NÃO TER CRIADO ANUNCIO PAGO  -->
				<div class="gerof">
					<a title="Você precisa Criar um Anuncio." style="color:#FFF;" href="#"> 
						<p style="color:#FFF; font-size:9pt; font-family: 'Ubuntu', sans-serif; text-align:center;">
							Gerenciar Ofertas
						</p>
					</a>
				</div>
			</div>
			<!-- BOX VISUALIZARAM ANUNCIO APENAS PARA PGO -->     

			<!-- BOX MENSAGENS --> 
			<div style="background-image:url(/static/img/bx4.png);" class="bxst2">
				<!-- QUANTAS MENSAGENS--> 
				<div class="nmberancio2"> 
					<p style="color:#FFF; margin-top:-5px; font-size:24pt; font-family: 'Ubuntu', sans-serif; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						00
					</p> 
				</div>

				<div class="dvnme2"> 
					<p style="color:#FFF; margin-left:10px; font-size:13px; font-family: 'Ubuntu', sans-serif; margin-top:-8px; text-shadow: 0 0 1px rgba(0,0,0,.35);">
						Mensagens Não Lidas
					</p>
				</div>

				<div class="gerof">
					<a title="Ver Mensagens" style="color:#FFF;" href="#"> 
						<p style="color:#FFF; font-size:9pt; font-family: 'Ubuntu', sans-serif; text-align:center;">
							Ver Mensagens
						</p>
					</a>
				</div>
			</div>
		<!-- BOX MENSAGENS -->  
		</div>
		{% if anuncio_gratis %}
				
			<!-- BOX STATUS ANUNCIO -->  
			<div class="sttsanuncios">
				<div  class="sidttleanc"> 
					<div style="margin-left:10px;" class="tpsv"> 
						<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#38538e;">
							<strong>Produto/Serviço</strong>
						</p>
					</div>

					<div style="margin-left:310px;" class="tpsv">
						<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#38538e">
							<strong>Tipo</strong>
						</p>
					</div>

					<div style="margin-left:180px;" class="tpsv">
						<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#38538e">
							<strong>Ações</strong>
						</p>
					</div>
				</div>

			{% for anuncio in anuncio_gratis %}
				<!-- STATUS DOS ANUNCIOS -->
				<div class="anuncstat"> 
					<div class="bxnmesv">
						<a style="color:#38538e; text-decoration:underline; " title="Seu Anúncio" href="#">
							<p style="font-family:arial; font-size:10pt; margin-top:10px;">
								{{anuncio.titulo}}
							</p>
						</a> 
					</div>

					<div style="margin-left:20px; float:left;" class="bxnmesv2">
						<p style="color:#38538e; font-family:arial; font-size:10pt; margin-top:10px;">
							Grátis/Free
						</p> 
					</div>

					<!-- BOTAO EDITAR O ANUNCIO -->
					<a title="Editar seu Anúncio" href="#">
						<div style="margin-left:200px; float:left;" class="bxnmesv2">
							<p style="color:#09F; font-family:arial; font-size:9pt; margin-top:10px;">
								<span style="background-image:url(/static/img/eddt.png);" class="bsxico"></span>
								<span style="margin-left:5px; float:left; margin-top:2px; ">
									<strong>Album</strong>
								</span>
							</p> 
						</div>
					</a>
					<!-- FIM BOTAO EDITAR O ANUNCIO -->
					
					<!-- BOTAO EDITAR O ANUNCIO -->
					<a title="Editar seu Anúncio" href="#">
						<div style="margin-left:20px; float:left;" class="bxnmesv2">
							<p style="color:#09F; font-family:arial; font-size:9pt; margin-top:10px;">
								<span style="background-image:url(/static/img/eddt.png);" class="bsxico"></span>
								<span style="margin-left:5px; float:left; margin-top:2px; ">
									<strong>Editar</strong>
								</span>
							</p> 
						</div>
					</a>

					<!-- BOTAO EXCLUIR O ANUNCIO -->
					<a title="Excluir seu Anúncio" href="#">
						<div style="margin-left:20px; float:left;" class="bxnmesv2">
							<p style="color:#09F; font-family:arial; font-size:9pt; margin-top:10px;">
								<span style="background-image:url(/static/img/ext.png);" class="bsxico"></span>
								<span style="margin-left:5px; float:left; margin-top:2px; "> 
									<strong>Excluir</strong>
								</span>
							</p> 
						</div>
					</a>
					<!-- FIM BOTAO EDITAR O ANUNCIO --> 
				</div> <!--FIM DO STATUS DOS ANUNCIOS -->
			</div>
			<!-- BOX STATUS ANUNCIO --> 
			{% endfor %}
		{% else %}
		<!-- BOX STATUS ANUNCIO -->  
		<div class="sttsanuncios"> 
			<div  class="sidttleanc"> 
				<div style="margin-left:10px;" class="tpsv">
					<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#38538e;">
						<strong>
							Produto/Serviço
						</strong>
					</p>
				</div>

				<div style="margin-left:310px;" class="tpsv">
					<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#CCC">
						<strong>
							Tipo
						</strong>
					</p>
				</div>  

				<div style="margin-left:30px;" class="tpsv">
					<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#CCC">
						<strong>
							Valor
						</strong>
					</p>
				</div>  

				<div style="margin-left:10px;" class="tpsv">
					<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#CCC">
						<strong>
							Ciclo de Pagamento
						</strong>
					</p>
				</div>

				<div style="margin-left:35px;" class="tpsv">
					<p style=" font-size:13px; margin-top:2px; font-family: 'Open Sans', sans-serif; color:#CCC;">
						<strong>
							Próximo Vencimento
						</strong>
					</p>
				</div>  
			</div>

			<!-- STATUS DOS ANUNCIOS -->
			<div class="anuncstat"> 	
				<div class="bxnmesv">
					<a style="  color:#09F; text-decoration:underline; " title="Crie seu Anuncio Agora!" href="/planos"> 
						<p style="font-family:arial; font-size:10pt; margin-top:10px;">
							Crie seu Anúncio Agora!
						</p>
					</a>
				</div>
			</div> <!--FIM DO STATUS DOS ANUNCIOS -->	
		</div>

		<!-- BOX STATUS ANUNCIO --> 
		{% endif %}

		<!-- DADS USER, RESUM --> 
		<div class="bxdescdados"> 	
			<!-- INFORMACOES DO USUARIO RESUMIDAS -->
			<div class="bxdads"> 
				<div class="sdtxs">
					<span style=" float:left; margin-top:11px; margin-left:10px;">
						Informações da Conta
					</span>
				</div>

				<div class="sddts"> 
					 <!-- NOME,sobrenome e (Empresa) -->
					<div class="snme"> 
						<span style="font-family: 'Ubuntu', sans-serif; font-size:12pt; margin-left:10px;">
							{{user.usuario.nome}}
						</span>
					</div>

					<!-- ENDEREÇO, bairro -->
					<div class="snme2">
						<!-- ENDEREÇO --> 
						<span style="font-family:arial; font-size:11pt; margin-left:10px;"> {{user.usuario.endereco}} -
						<!-- Bairro --> 
							<span> 
								{{user.usuario.bairro}}
							</span>
						</span>
					</div>

					<!-- Cidade,estado,cep -->
					<div class="snme2">
						<!-- CITY --> 
						<span style="font-family:arial; font-size:11pt; margin-left:10px;"> {{user.usuario.cidade}},
						<!-- Bairro --> 
							<span> {{user.usuario.estado}} </span>,
						<!-- CEP --> 
							<span> {{user.usuario.cep}} </span>	
						</span>
					</div>
					
					<!-- EMAIL -->
					<div class="snme2">
					<!-- EMAIL -->
						<a href='mailto:{{user.email}}'> 
							<span style="font-family:arial; font-size:11pt; margin-left:10px;">{{user.email}}</span>
						</a>
					</div>

					<a title="Atualizar seus Dados" href="#">
						<div class="bxatulizdads"> 
							<div class="bxatulizdads2">
								<div class="icv"> </div>
								<span style="color:#333; float:left; margin-top:7px;"> Atualizar seus Dados </span>
							</div>
						</div>
					</a>			
				</div>
			</div>  <!-- FIM INFORMACOES DO USUARIO RESUMIDAS -->
		
			<!-- ADSENSE -->
			<div class="bxads">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- blocopainel -->
				<ins class="adsbygoogle"
					 style="display:inline-block;width:336px;height:280px"
					 data-ad-client="ca-pub-4072787528957271"
					 data-ad-slot="7919976462"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
			<!-- FIM ADSENSE -->

		</div> <!-- FIM DADS USER, RESUM --> 
		<div class="separcont"> </div>
		</div>
	</div> <!-- FIM DIV QUE CENTRALIZA --> 
{% endblock conteudo %}